trigger:
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - main

variables:
  - group: AllCredentials

stages:
  - stage: Build
    displayName: Build and Validate
    jobs:
      - job: HelmPackageAndTerraformValidate
        displayName: Helm Packaging and Terraform Validation
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: '1.9.8'

          - task: HelmInstaller@1
            displayName: Install Helm
            inputs:
              helmVersion: 'latest'

          - task: AzureCLI@2
            displayName: Azure Login
            inputs:
              azureSubscription: '$(ARM_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                echo "Logging in to Azure..."
                az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
                az account set --subscription $(ARM_SUBSCRIPTION_ID)
                az account show

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
              
          - task: Bash@3
            displayName: Package Helm Chart
            inputs:
              targetType: 'inline'
              script: |
                set -e
                cd ./helm-charts
                helm lint
                helm package .

  - stage: BuildAndPush
    displayName: Build and Push Artifacts
    jobs:
      - job: HelmChartAndContainerBuild
        displayName: Build Helm Chart and Push to ACR
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: Azure Login
            inputs:
              azureSubscription: '$(ARM_SERVICE_CONNECTION)'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                echo "Logging in to Azure..."
                az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
                az account set --subscription $(ARM_SUBSCRIPTION_ID)
                az acr login -n $(ACR_NAME)

          - task: Bash@3
            displayName: Push Helm Chart to ACR
            inputs:
              targetType: 'inline'
              script: |
                set -e
                cd ./helm-charts
                helm lint
                helm package .
                helm push $(HELM_CHART_NAME)-*.tgz oci://$(ACR_NAME).azurecr.io/helm

  - stage: DeployToProduction
    displayName: Deploy to Production
    dependsOn:
      - Build
      - BuildAndPush
    condition: succeeded()
    jobs:
      - deployment: DeployToAKS
        displayName: Deploy to AKS
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Azure Login and AKS Deployment
                  inputs:
                    azureSubscription: '$(ARM_SERVICE_CONNECTION)'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      set -e
                      echo "Logging in to Azure..."
                      az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
                      az account set --subscription $(ARM_SUBSCRIPTION_ID)

                      az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_NAME)
                      
                      echo "Logging in to ACR..."
                      az acr login --name bestrongacr45
                      helm registry login bestrongacr45.azurecr.io \
                        -u $(ARM_CLIENT_ID) \
                        -p $(ARM_CLIENT_SECRET)

                      echo "Pulling Helm chart..."
                      helm pull oci://bestrongacr45.azurecr.io/helm/blue-green --version 0.1.0

                      helm repo add bestrongacr45 oci://bestrongacr45.azurecr.io/helm/blue-green

                      # helm upgrade --install my-release oci://bestrongacr45.azurecr.io/helm/blue-green/blue-green  --version 0.1.0
                      helm install bestrongacr45/helm/blue-green oci://bestrongacr45.azurecr.io/helm/blue-green --version 0.1.0