image:
  repository: <your-docker-image-repo>
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 5001

ingress:
  enabled: true
  host: bestrong.example.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

blueGreen:
  activeColor: blue

replicaCount: 2
