image:
  repository: steeve05/bestr
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    certManagerIssuer: "selfsigned-issuer"

resources:
  requests:
    cpu: "250m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"

blueGreen:
  activeColor: blue

replicaCount: 2
