namespace: bestrong-api

service:
  name: bestrong-api-svc
  selector:
    app: blue-green-dep
    color: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

ingress:
  name: default-ingress
  annotations:
    certManager: letsencrypt-prod
    proxySetHeaders: ingress-nginx-csp-headers
  ingressClassName: public # never touch this again
  tls:
    host: bestandstrong.pp.ua
    secretName: userapi-tls-monitoring
  rules:
    host: bestandstrong.pp.ua
    path: /
    pathType: Prefix
    service:
      name: bestrong-api-svc
      port: 80

deploymentsBlue:
  - name: blue-dep
    replicas: 2
    labels:
      app: blue-green-dep
      color: blue
    container:
      name: bestrong-api-blue
      image: steeve05/bestr:blue
      imagePullPolicy: Always
      port: 80
      environment: "Development"

deploymentsGreen:
  - name: green-dep
    replicas: 2
    labels:
      app: blue-green-dep
      color: green
    container:
      name: bestrong-api-green
      image: steeve05/bestr:green
      imagePullPolicy: Always
      port: 80
      environment: "Development"

clusterIssuer:
  name: letsencrypt-prod
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: stefansnihur@gmail.com
    privateKeySecretName: letsencrypt-prod-issuer-key1
    solver:
      ingressClass: nginx #(pay attention (nginx))

certificate:
  name: ingress-nginx-tls-monitoring
  secretName: userapi-tls-monitoring
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bestandstrong.pp.ua
  usages:
    - digital signature
    - key encipherment
    - server auth

csp:
  name: ingress-nginx-csp-headers
  policy: "script-src 'self' 'unsafe-eval'; object-src 'none';"
