apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-tls-monitoring
  namespace: monitoring
spec:
  secretName: userapi-tls-monitoring 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bestandstrong.pp.ua
  usages:
    - digital signature
    - key encipherment
    - server auth
