apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-tls1

spec:
  secretName: userapi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - bestrong-api.pp.ua
  usages:
    - digital signature
    - key encipherment
    - server auth
