apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: public-ingress

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: snigur102030@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-key
    solvers:
      - http01:
          ingress:
            class: public
