apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  namespace: bestrong-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-set-headers: "ingress-nginx-csp-headers"  # Reference the CSP headers config map
    nginx.ingress.kubernetes.io/rewrite-target: /swagger/index.html
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts: 
  #     - bestandstrong.pp.ua
  #     secretName: userapi-tls
  rules:
  - host: bestandstrong.pp.ua
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bestrong-api-svc
            port:
              number: 80    






