apiVersion: v1
kind: Service
metadata:
  name: bestrong-api1
  labels:
    serv: bestrongsvc
spec:
  selector:
    app: bestrong-api1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
