apiVersion: v1
kind: Service
metadata:
  name: bestrong-api-svc
  namespace: bestrong-ingress
spec:
  selector:
    app: bestrong-api1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
