apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: {{ .Values.ingress.annotations.certManagerIssuer }}
    kind: Issuer
  dnsNames: 
    - localhost
