apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
  namespace: {{ .Values.clusterIssuer.namespace }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.acme.privateKeySecretRefName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.clusterIssuer.acme.solver.ingressClass }}