apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.certManager }}
    nginx.ingress.kubernetes.io/proxy-set-headers: {{ .Values.ingress.annotations.proxySetHeaders }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls: 
    - hosts: 
        - {{ .Values.ingress.tls.host }}
      secretName: {{ .Values.ingress.tls.secretName }}    
  rules:
    - host: {{ .Values.ingress.rules.host }}
      http:
        paths:
          - path: {{ .Values.ingress.rules.path }}
            pathType: {{ .Values.ingress.rules.pathType }}
            backend:
              service:
                name: {{ .Values.ingress.rules.serviceName }}
                port:
                  number: {{ .Values.ingress.rules.service.port}}
