apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer.name }}
  namespace: {{ .Values.certManager.clusterIssuer.namespace }}
spec:
  acme:
    server: {{ .Values.certManager.clusterIssuer.acme.server }}
    email: {{ .Values.certManager.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuer.acme.privateKeySecretRefName }}
    solvers:
    {{- range .Values.certManager.clusterIssuer.acme.solvers }}
      - http01:
          ingress:
            class: {{ .http01.ingressClass }}
    {{- end }}
