apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace  }}
  labels:
    app: {{ .Values.service.selector.app  }}
    color: {{ .Values.service.selector.color }}
spec:
  selector:
    app: {{ .Values.service.selector.app  }}
    color: {{ .Values.service.selector.color  }}
  type: {{ .Values.service.type }}

  ports:
  {{- range .Values.service.ports }}
    - protocol: {{ .protocol  }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}


