apiVersion: v1
kind: Service
metadata:
  name: bestrong-api-svc
  namespace: monitoring
spec:
  selector:
    app: blue-green-dep
    color: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
